"""add device description

Revision ID: 2e008caa68fa
Revises: fdf0581fb74e
Create Date: 2026-08-21 15:42:40.970356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e008caa68fa'
down_revision: Union[str, Sequence[str], None] = 'fdf0581fb74e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_access_log_device'), 'access_log', type_='foreignkey')
    op.create_foreign_key(None, 'access_log', 'device', ['device_id'], ['id'], ondelete='RESTRICT')
    op.add_column('device', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'description')
    op.drop_constraint(None, 'access_log', type_='foreignkey')
    op.create_foreign_key(op.f('fk_access_log_device'), 'access_log', 'device', ['device_id'], ['id'])
    # ### end Alembic commands ###
